package com.spakborhills.model.Enum;

public enum TutorialStep {
    NONE,
    INTRO_MAYOR_WELCOME, 
    EXPLAIN_MOVEMENT,
    GO_TO_MAYOR_HOUSE, 
    MAYOR_HOUSE_WELCOME, 
    EXPLAIN_TOOLS_AND_ENERGY, 
    EXPLAIN_SEEDS_BUYING, 
    GO_TO_SHOP, 
    SHOP_WELCOME_EMILY,
    BOUGHT_FIRST_SEEDS, 
    EXPLAIN_TILLING_AND_PLANTING, 
    PLANTED_FIRST_CROP, 
    EXPLAIN_WATERING,
    WATERED_FIRST_CROP, 
    EXPLAIN_HARVESTING,
    HARVESTED_FIRST_CROP, 
    EXPLAIN_SELLING_SHIPPING_BIN, 
    SOLD_FIRST_CROP_BIN, 
    EXPLAIN_FISHING, 
    GO_TO_RIVER, 
    CAUGHT_FIRST_FISH,
    EXPLAIN_SELLING_GENERAL_STORE, 
    SOLD_FIRST_FISH_STORE, 
    MAYOR_CONGRATS_BASICS, 
    TUTORIAL_COMPLETE 
}